apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "actions-runner-controller"
  namespace: "argocd"
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: actions-runner-controller
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - git@github.com:fotomerchant/eks-blueprints-add-ons.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  labels:
    env: jaytring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: workflows/jaytring
    repoURL: 'git@github.com:fotomerchant/eks-blueprints-add-ons.git'
    targetRevision: feature/fep-7-blueprint-integration
    helm:
      actions-runner-controller:
        enable: true
        createNamespace: true
        authSecret:
          create: true
          github_token: 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
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Big CRDs.

