apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "actions-runner-controller"
  namespace: "argocd"
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: actions-runner-controller
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - git@github.com:fotomerchant/eks-blueprints-add-ons.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  labels:
    env: jaytring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "actions-runner-controller"
  source:
    path: workflows/jaytring
    repoURL: 'git@github.com:fotomerchant/eks-blueprints-add-ons.git'
    targetRevision: feature/fep-7-blueprint-integration
    helm:
      enable: true
      authSecret:
        create: true
      createNamespace: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: "argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: workflows/jaytring
    repoURL: 'git@github.com:fotomerchant/eks-blueprints-add-ons.git'
    targetRevision: feature/fep-7-blueprint-integration
  destination:
    server: "https://kubernetes.default.svc"
    namespace: workloads
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

