# Helm chart values
extraArgs:
  - --enable-certificate-owner-ref=true
installCRDs: true
serviceAccount:
  create: true
  name: cert-manager
serviceAccountName: cert-manager
securityContext:
  fsGroup: 1001
