{{- if .Values.apps.console.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject-orders-group4
  namespace: fmhv
spec:
  scaleTargetRef:
    name: orders-group4
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.awsAccountId }}/hv-plic_orders
        queueLength: "50"
        awsRegion: "{{ .Values.awsRegion }}"
        identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject-orders-group4-1
  namespace: fmhv
spec:
  scaleTargetRef:
    name: orders-group4-1
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.awsAccountId }}/hv-batch_order_item_build_job.fifo
        queueLength: "50"
        awsRegion: "{{ .Values.awsRegion }}"
        identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject-orders-group4-2
  namespace: fmhv
spec:
  scaleTargetRef:
    name: orders-group4-2
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.{{ .Values.awsRegion }}.amazonaws.com/{{ .Values.awsAccountId }}/hv-batch_order_distribution.fifo
        queueLength: "50"
        awsRegion: "{{ .Values.awsRegion }}"
        identityOwner: operator
{{- end }}
