cert-manager:
  extraArgs:
  - --enable-certificate-owner-ref=true
  installCRDs: true
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::{{.Values.account}}:role/{{.Values.clusterName}}-cert-manager-sa-irsa
