cert-manager:
  extraArgs:
  - --enable-certificate-owner-ref=true
  installCRDs: true
  serviceAccount:
    create: true
    name: cert-manager
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::fixed:role/fixed-cert-manager-sa-irsa
  serviceAccountName: cert-manager
  securityContext:
    fsGroup: 1001
