apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-cm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
data:
  DOCUMENT_ROOT: "/usr/src/app/public"
  SCRIPT_FILENAME: "/usr/src/app/public/index.php"
  HTTP_PROXY: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
  labels:
    tier: backend
data:
  config : |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /usr/src/app/public;

      #location / {
      #    try_files $uri $uri/ /index.php?$query_string;
      #}

      #location ~ [^/]\.php(/|$) {
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 64 4k;
        fastcgi_busy_buffers_size 224k;
        #if (!-f $document_root$fastcgi_script_name) {
        #    return 404;
        #}

        # Mitigate https://httpoxy.org/ vulnerabilities
        # fastcgi_param HTTP_PROXY "";

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_index index.php;

        # include the fastcgi_param setting
        include fastcgi_params;

        # SCRIPT_FILENAME parameter is used for PHP FPM determining
        #  the script name. If it is not set in fastcgi_params file,
        # i.e. /etc/nginx/fastcgi_params or in the parent contexts,
        # please comment off following line:
        # fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
    }
