apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: fmhv
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@fotomerchant.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
