apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: fmhv
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@fotomerchant.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx