apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvL2ZvdG9tZXJjaGFudC9odiI6eyJ1c2VybmFtZSI6ImpheXRyaW5nZm0iLCJwYXNzd29yZCI6ImdocF9xbmVvSmxPcXZMVFpYYmN6OFlFUlJLOWFzb0RpSGQzRW45VloifX19Cg==
kind: Secret
metadata:
  name: eks-argocd-github-packages-token
  namespace: fmhv
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fmhv-db-rebuild
  namespace: fmhv
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-options: Prune=false
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.awsAccountId }}:role/fmhv-db-rebuild-{{ .Values.clusterName }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fmhv-app
  namespace: fmhv
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-options: Prune=false
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.awsAccountId }}:role/fmhvApp-{{ .Values.clusterName }}"
