enable: true
createNamespace: true
authSecret:
  create: true
  github_token: ssss

actions-runner-controller:
  enable: true
  createNamespace: true
  authSecret:
    create: true
    github_token: ssss
